export const homepageTourSteps = [
  {
    target: ".side-button-map",
    content: "Explore the map to find places and plan your route.",
    disableBeacon: true,
    placement: "auto",
    title: "Interactive Map",
    titleTl: "Interactive Map",
    contentTl:
      "Silipin ang map para makita ang mga lugar at planuhin ang ruta mo.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".side-button-itinerary",
    content: "Create your tour. Pick your preferred places",
    placement: "auto",
    title: "Tour Plans",
    titleTl: "Tour Plans",
    contentTl: "Gumawa ng tour. Piliin ang mga gusto mong lugar",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".side-button-photobooth",
    content: "Take photos with filters and frames.",
    placement: "auto",
    title: "Photo Booth",
    titleTl: "Photo Booth",
    contentTl: "Kunan ng picture gamit ang filters at frames.",
    avatar: "/juan/Juan3.png",
  },
  {
    target: ".side-button-emergency",
    content: "Quick access to hotlines and key contacts.",
    placement: "auto",
    title: "Emergency Contacts",
    titleTl: "Mga Emergency Contact",
    contentTl: "Mabilis na access sa hotlines at contacts.",
    avatar: "/juan/Juan4.png",
  },
  {
    target: ".side-button-profile",
    content: "Manage your profile and preferences.",
    placement: "auto",
    title: "Profile Settings",
    titleTl: "Mga Setting ng Profile",
    contentTl: "Ayusin ang profile.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".side-button-archives",
    content: "See your past trips, photos, and reviews.",
    placement: "auto",
    title: "Trip Archives",
    titleTl: "Trip Archives",
    contentTl: "Tingnan ang past trips, photos, at reviews.",
    avatar: "/juan/Juan3.png",
  },
  {
    target: ".floating-chatbot",
    content: "Ask Juan about Intramuros.",
    placement: "auto",
    title: "AI Chatbot",
    titleTl: "AI Chatbot",
    contentTl: "Magtanong kay Juan tungkol sa Intramuros.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".homepage-start-tour-btn",
    content: "Start your tour or view the map.",
    placement: "auto",
    title: "Start Tour",
    titleTl: "Simulan ang Tour",
    contentTl: "I-start ang tour o i-view ang map",
    avatar: "/juan/Juan3.png",
  },
];

// Guided tour for itinerary map pages (tourist and guest)
export const mapTourSteps = [
  {
    target: ".map-tts-toggle",
    content: "Toggle voice directions.",
    placement: "auto",
    title: "Voice Guidance",
    titleTl: "Voice Guidance",
    contentTl: "On/off ang voice directions.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".map-center-btn",
    content: "Center the map to your location.",
    placement: "auto",
    title: "My Location",
    titleTl: "Aking Lokasyon",
    contentTl: "I-sentro ang map sa lokasyon mo.",
    avatar: "/juan/Juan3.png",
  },
  {
    target: ".map-show-destination-btn",
    content: "See destination details.",
    placement: "auto",
    title: "Current Destination",
    titleTl: "Kasalukuyang Destinasyon",
    contentTl: "Tingnan ang details ng destinasyon.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".map-transport-button",
    content: "Choose Foot, Bike, or Car.",
    placement: "auto",
    title: "Transport Mode",
    titleTl: "Paraan ng Biyahe",
    contentTl: "Pumili ng Lakad, Bike, o Kotse.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".direction-prev-btn",
    content: "Go back to the previous place.",
    placement: "auto",
    title: "Previous Place",
    titleTl: "Nakaraang Lugar",
    contentTl: "Bumalik sa naunang lugar.",
    avatar: "/juan/Juan4.png",
  },
  {
    target: ".direction-skip-btn",
    content: "Skip this place.",
    placement: "auto",
    title: "Skip Place",
    titleTl: "Laktawan ang Lugar",
    contentTl: "Laktawan ang lugar na ito.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".direction-next-btn",
    content: "Go to the next place. End when you're done.",
    placement: "auto",
    title: "Next / End Tour",
    titleTl: "Susunod / Tapusin",
    contentTl: "Punta sa next na lugar. Tapusin kapag huli na.",
    avatar: "/juan/Juan3.png",
  },
];

export const guestTourSteps = [
  {
    target: ".side-button-map",
    content: "Explore the map for places.",
    disableBeacon: true,
    placement: "auto",
    title: "Interactive Map",
    titleTl: "Interactive na Mapa",
    contentTl: "Silipin ang mapa para sa mga lugar.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".side-button-itinerary",
    content: "Browse tour plans. Sign up to save your routes.",
    placement: "auto",
    title: "Tour Plans",
    titleTl: "Tour Plans",
    contentTl:
      "Mag-browse ng tour plans. Mag-sign up para ma-save ang ruta mo.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".side-button-photobooth",
    content: "Try the AR photobooth.",
    placement: "auto",
    title: "Photo Booth",
    titleTl: "Photo Booth",
    contentTl: "Subukan ang AR photobooth.",
    avatar: "/juan/Juan3.png",
  },
  {
    target: ".side-button-emergency",
    content: "Quick access to hotlines and contacts.",
    placement: "auto",
    title: "Emergency Contacts",
    titleTl: "Mga Emergency Contact",
    contentTl: "Mabilis na access sa hotlines at contacts.",
    avatar: "/juan/Juan4.png",
  },
  {
    target: ".side-button-profile",
    content: "Open profile settings. Sign up to save.",
    placement: "auto",
    title: "Profile Settings",
    titleTl: "Mga Setting ng Profile",
    contentTl: "Buksan ang profile settings. Mag-sign up para ma-save.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".side-button-archives",
    content: "See past trips, photos, and memories.",
    placement: "auto",
    title: "Trip Archives",
    titleTl: "Trip Archives",
    contentTl: "Tingnan ang past trips, photos, at alaala.",
    avatar: "/juan/Juan4.png",
  },
  {
    target: ".floating-chatbot",
    content: "Ask the AI Chatbot. Drag to move.",
    placement: "auto",
    title: "Juan",
    titleTl: "AI Chatbot",
    contentTl: "Magtanong sa AI Chatbot. I-drag para ilipat.",
    avatar: "/juan/Juan4.png",
  },
];

export const createItineraryTourSteps = [
  {
    target: ".itinerary-tab-create-btn",
    content: "Create and name your tour plan.",
    placement: "auto",
    title: "Create Tour Plan",
    titleTl: "Gumawa ng Tour Plan",
    contentTl: "Gumawa at pangalanan ang tour plan mo.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".create-itinerary-search",
    content: "Search and filter places.",
    placement: "auto",
    title: "Search & Filter",
    titleTl: "Hanapin at I-filter",
    contentTl: "Maghanap at mag-filter ng mga lugar.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".create-itinerary-add-btn",
    content: "Tap to add a place.",
    placement: "auto",
    title: "Add Place",
    titleTl: "Magdagdag ng Lugar",
    contentTl: "I-tap para magdagdag ng lugar.",
    avatar: "/juan/Juan3.png",
  },
  {
    target: ".create-itinerary-save-btn",
    content: "Save your tour plan.",
    placement: "auto",
    title: "Save Tour Plan",
    titleTl: "I-save ang Tour Plan",
    contentTl: "I-save ang tour plan.",
    avatar: "/juan/Juan4.png",
  },
  {
    target: ".my-itineraries-tab-btn",
    content: "Manage your saved tour plans.",
    placement: "auto",
    title: "My Tour Plans",
    titleTl: "Mga Tour Plan Ko",
    contentTl: "I-manage ang mga na-save mong tour plans.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".my-itinerary-edit-btn",
    content: "Rename or change places.",
    placement: "auto",
    title: "Edit",
    titleTl: "I-edit",
    contentTl: "Palitan ang pangalan o baguhin ang mga lugar.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".my-itinerary-delete-btn",
    content: "Delete a tour plan.",
    placement: "auto",
    title: "Delete",
    titleTl: "I-delete",
    contentTl: "Tanggalin ang tour plan.",
    avatar: "/juan/Juan3.png",
  },
  {
    target: ".my-itinerary-view-sites-btn",
    content: "Expand to see places.",
    placement: "auto",
    title: "View Places",
    titleTl: "Tingnan ang mga Lugar",
    contentTl: "Palawakin para makita ang mga lugar.",
    avatar: "/juan/Juan4.png",
  },
];

export const emergencyTourSteps = [
  {
    target: ".emergency-first-contact",
    content: "Tap to call the main contact.",
    placement: "auto",
    title: "Emergency Contact",
    titleTl: "Emergency Contact",
    contentTl: "I-tap para tumawag sa pangunahing contact.",
    avatar: "/juan/Juan4.png",
  },
];

export const profileTourSteps = [
  {
    target: ".profile-option-account",
    content: "Manage your account info.",
    placement: "auto",
    title: "Account",
    titleTl: "Account",
    contentTl: "Ayusin ang account info mo.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".profile-option-birthday",
    content: "Set your birthday.",
    placement: "auto",
    title: "Birthday",
    titleTl: "Kaarawan",
    contentTl: "Itakda ang birthday mo.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".profile-option-gender",
    content: "Update your gender.",
    placement: "auto",
    title: "Gender",
    titleTl: "Kasarian",
    contentTl: "I-update ang gender mo.",
    avatar: "/juan/Juan3.png",
  },
  {
    target: ".profile-option-country",
    content: "Select your country.",
    placement: "auto",
    title: "Country",
    titleTl: "Bansa",
    contentTl: "Piliin ang bansa mo.",
    avatar: "/juan/Juan4.png",
  },
  {
    target: ".profile-option-language",
    content: "Choose your language.",
    placement: "auto",
    title: "Language",
    titleTl: "Wika",
    contentTl: "Piliin ang wika mo.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".profile-option-settings",
    content: "Configure notifications and tutorials.",
    placement: "auto",
    title: "Settings",
    titleTl: "Mga Setting",
    contentTl: "Ayusin ang notifications at tutorials.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".profile-logout-btn",
    content: "Log out safely.",
    placement: "auto",
    title: "Logout",
    titleTl: "Mag-logout",
    contentTl: "Mag-logout nang ligtas.",
    avatar: "/juan/Juan3.png",
  },
];

export const guestProfileTourSteps = [
  {
    target: ".guest-option-language",
    content: "Change language in guest mode.",
    placement: "auto",
    title: "Language",
    titleTl: "Wika",
    contentTl: "Palitan ang wika sa guest mode.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".guest-option-settings",
    content: "Adjust guest settings.",
    placement: "auto",
    title: "Settings",
    titleTl: "Mga Setting",
    contentTl: "Ayusin ang guest settings.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".guest-create-account-btn",
    content: "Create an account to unlock features.",
    placement: "auto",
    title: "Create Account",
    titleTl: "Gumawa ng Account",
    contentTl: "Gumawa ng account para ma-unlock ang features.",
    avatar: "/juan/Juan3.png",
  },
];

export const photoboothTourSteps = [
  {
    target: ".photobooth-slider",
    content: "Swipe to choose a filter.",
    placement: "auto",
    title: "Filters Slider",
    titleTl: "Slider ng Filter",
    contentTl: "I-swipe para pumili ng filter.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".photobooth-capture-btn",
    content: "Tap to take a photo.",
    placement: "auto",
    title: "Capture",
    titleTl: "Kunan",
    contentTl: "I-tap para kumuha ng larawan.",
    avatar: "/juan/Juan2.png",
  },
];

export const tourMapSteps = [
  {
    target: ".map-search-btn-left",
    content: "Search for any place.",
    placement: "right",
    title: "Search",
    titleTl: "Hanapin",
    contentTl: "Maghanap ng kahit anong lugar.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".map-first-pin",
    content: "Tap a map marker for details.",
    placement: "auto",
    title: "Map Markers",
    titleTl: "Mga Marker",
    contentTl: "I-tap ang marker sa mapa para sa details.",
    avatar: "/juan/Juan2.png",
  },
];

export const tripArchiveTourSteps = [
  {
    target: ".trip-tab-places-btn",
    content: "Open your visited places.",
    placement: "auto",
    title: "Places",
    titleTl: "Mga Lugar",
    contentTl: "Buksan ang mga napuntahan.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".trip-place-card",
    content: "See details of a visited place.",
    placement: "auto",
    title: "Visited Places",
    titleTl: "Napuntahang Lugar",
    contentTl: "Tingnan ang detalye ng napuntahan.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".trip-tab-reviews-btn",
    content: "Open reviews.",
    placement: "auto",
    title: "Review",
    titleTl: "Mga Review",
    contentTl: "Buksan ang reviews.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".trip-write-review-btn",
    content: "Write a review.",
    placement: "auto",
    title: "Write Review",
    titleTl: "Gumawa ng Review",
    contentTl: "Gumawa ng review.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".trip-edit-review-btn",
    content: "Edit your review.",
    placement: "auto",
    title: "Edit Review",
    titleTl: "I-edit ang Review",
    contentTl: "I-edit ang review mo.",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".trip-delete-review-btn",
    content: "Delete your review.",
    placement: "auto",
    title: "Delete Review",
    titleTl: "I-delete ang Review",
    contentTl: "Burahin ang review mo.",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".trip-tour-ender",
    content: "You're set. See your past trips.",
    placement: "auto",
    title: "Get Started",
    titleTl: "Handa ka na",
    contentTl: "Handa ka na. Silipin ang past trips mo.",
    avatar: "/juan/Juan3.png",
  },
];
