export const homepageTourSteps = [
  {
    target: ".side-button-map",
    content: "Explore the interactive map of Intramuros to discover historical sites and plan your route through the walled city.",
    disableBeacon: true,
    placement: "auto",
    title: "Interactive Map",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".side-button-itinerary",
    content: "Create personalized tour itineraries by selecting sites you want to visit. We'll help you optimize your route.",
    placement: "auto",
    title: "Tour Itineraries",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".side-button-photobooth",
    content: "Capture memories with our AR photobooth featuring historical filters and border assets.",
    placement: "auto",
    title: "Photo Booth",
    avatar: "/juan/Juan3.png",
  },
  {
    target: ".side-button-emergency",
    content: "Quick access to emergency hotlines and important contacts for your safety during your visit.",
    placement: "auto",
    title: "Emergency Contacts",
    avatar: "/juan/Juan4.png",
  },
  {
    target: ".side-button-profile",
    content: "Manage your profile settings and customize your experience.",
    placement: "auto",
    title: "Profile Settings",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".side-button-archives",
    content: "Review your past visits, photos, and reviews. Trip Archives helps you revisit memories and manage your experiences.",
    placement: "auto",
    title: "Trip Archives",
    avatar: "/juan/Juan3.png",
  },
  {
    target: ".floating-chatbot",
    content: "Your AI tour guide Juan is here to help! Ask questions about Intramuros history, directions, or recommendations. Drag this icon to reposition it anywhere on screen.",
    placement: "auto",
    title: "AI Tour Guide",
    avatar: "/juan/Juan2.png",
  },
];

export const guestTourSteps = [
  {
    target: ".side-button-map",
    content: "Explore the interactive map to discover Intramuros' historical sites and landmarks.",
    disableBeacon: true,
    placement: "auto",
    title: "Interactive Map",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".side-button-itinerary",
    content: "Browse available tour itineraries. Sign up to create and save your own custom routes.",
    placement: "auto",
    title: "Tour Itineraries",
    avatar: "/juan/Juan2.png",
  },
  {
    target: ".side-button-photobooth",
    content: "Try our AR photobooth with historical filters and commemorative borders.",
    placement: "auto",
    title: "Photo Booth",
    avatar: "/juan/Juan3.png",
  },
  {
    target: ".side-button-emergency",
    content: "Quick access to emergency hotlines and important contacts for your safety during your visit.",
    placement: "auto",
    title: "Emergency Contacts",
    avatar: "/juan/Juan4.png",
  },
  {
    target: ".side-button-profile",
    content: "Access profile settings. Sign up or log in to save preferences.",
    placement: "auto",
    title: "Profile Settings",
    avatar: "/juan/Juan1.png",
  },
  {
    target: ".side-button-archives",
    content: "Review trips, photos, and memories in Trip Archives. Some features may require signup.",
    placement: "auto",
    title: "Trip Archives",
    avatar: "/juan/Juan4.png",
  },
  {
    target: ".floating-chatbot",
    content: "Your AI tour guide is ready to answer questions about Intramuros. Drag to reposition anywhere on screen.",
    placement: "auto",
    title: "AI Tour Guide",
    avatar: "/juan/Juan4.png",
  },
];