// Service Worker Registration with Auto-Update
export function registerServiceWorker() {
  // Only register in production
  if (import.meta.env.DEV) {
    return;
  }

  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      // The service worker file is auto-generated by vite-plugin-pwa
      navigator.serviceWorker
        .register('/sw.js', { scope: '/' })
        .then((registration) => {

          // Check for updates every 60 seconds
          setInterval(() => {
            registration.update();
          }, 60000);

          // Handle updates
          registration.addEventListener('updatefound', () => {
            const newWorker = registration.installing;

            newWorker.addEventListener('statechange', () => {
              if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                // Skip waiting and activate immediately
                newWorker.postMessage({ type: 'SKIP_WAITING' });
                
                // Show update notification (optional)
                showUpdateNotification();
              }
            });
          });

          // Listen for controller change (new SW activated)
          navigator.serviceWorker.addEventListener('controllerchange', () => {
            window.location.reload();
          });
        })
        .catch((error) => {
          // Silent fail
        });
    });
  }
}

function showUpdateNotification() {
  // Optional: Show a toast/notification to user
  // Auto-reload after a short delay
  setTimeout(() => {
    window.location.reload();
  }, 1000);
}
